### ISSUE TITLE
Error "slice indices must be integers..."

### ISSUE THREAD

**Issue by MOImaker** [jdber1/opendrop#13]
Hi, I'm trying to run the plugin on the following image:
![vlcsnap-2018-06-21-15h28m55s434](https://user-images.githubusercontent.com/39578081/41826358-2d5cf848-787d-11e8-99ed-03c6cd0fd662.png)

After selecting droplet region and needle region, I encounter the following error:
![error](https://user-images.githubusercontent.com/39578081/41826382-4c53aa58-787d-11e8-994f-adf0e6de8a23.PNG)

My gut tells me it's something to do with having a light droplet on dark background... and there is also poor lighting on the needle.

Any help would be appreciated :)

**Comment by askoufis** [comment]
This isn't a problem on your end but is actually a bug that was recently fixed in #11. There are two ways you can fix it:
1. If you've pulled the source code using git, then doing a `git pull` from the `master` branch will get you the latest version of the code that has the fix.
2. The easier method would be to download [this](https://raw.githubusercontent.com/jdber1/opendrop/67d8f7b937b6505a6c29cf2bf20850598893ae4e/modules/extract_profile.py) file and replace the file in `/modules/extract_profile.py` with it. I would suggest backing up your current `extract_profile.py` file just in case this doesn't work.

**Comment by MOImaker** [comment]
Thanks very much! 

I replaced the module and it's working now
