### ISSUE TITLE
opendrop not running in fedora 28

### ISSUE THREAD

**Issue by adityasuman2025** [jdber1/opendrop#19]
after installing opendrop when i type opendrop in terminal i am getting error:
Traceback (most recent call last):
  File "/usr/bin/opendrop", line 11, in <module>
    load_entry_point('opendrop==3.1.6.dev0', 'console_scripts', 'opendrop')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2421, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'

**Comment by eugenhu** [comment]
Sorry about the very late response. The development cycle of opendrop is kind of sporadic and quickly changing, so parts of the app might not have kept up with changes in other areas. In this case, it looks like an old version's installation script was broken and isn't calling the right starter function to begin the app.

If you're still interested in trying the app, the documentation is slightly out of date now, but the installation procedure is the same. However, the `opendrop` 'bootstrap' script that used to be placed in PATH has now been removed, so to start the app, you would run on the command line:
```
python3 -m opendrop
```

Also, make sure you install opendrop in a Python 3.8+ environment, this is the version currently being using for development so it should provide the best compatibility. Python 3.5+ support is targeted but is currently broken since some incompatible features were accidentally introduced.

**Comment by adityasuman2025** [comment]
its ok
