### ISSUE TITLE
Double-click exe to report  errors

### ISSUE THREAD

**Issue by shajingxin** [jdber1/opendrop#21]
Thanks for making the opendrop program.
         I have downloaded the latest version based on windows(opendrop3.6.1-windows), when i double-clicked the .exe file,it gave me bellow errors. i have already downloaded the UTK
![image](https://user-images.githubusercontent.com/70145377/91048273-02617380-e64e-11ea-9c82-8a62da6d8ebe.png)

![捕获](https://user-images.githubusercontent.com/70145377/91047971-823b0e00-e64d-11ea-9f13-1b3a7b37e8ca.PNG)

**Comment by eugenhu** [comment]
Thanks for the feedback.

Could you try re-extracting/re-downloading the zip file, and then running the app again? This error could be from missing or incompletely copied DLLs. Otherwise, could you also send a screenshot of the entire directory containing the opendrop.exe executable, including file sizes, so I can compare.

**Comment by shajingxin** [comment]
Thank you for your prompt reply ！
I changed the compression software and reunzipped the installation package as you suggested , it was successful.thank you!

**Comment by eugenhu** [comment]
No problems.
