### ISSUE TITLE
no setup.py installation error

### ISSUE THREAD

**Issue by prlw1** [jdber1/opendrop#24]
According to https://opendrop.readthedocs.io/en/latest/getting_started/index.html the magic command for installation is
```
pip install git+https://github.com/jdber1/opendrop.git
```
but this fails for me with
```
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-z6sowu38-build/setup.py'
```
In July, I see that commit a6283bba834aa3ec3eee432e6a12cfc41c04eaa7 removed setup.py. Is this related? Is there a new magic command?

**Comment by eugenhu** [comment]
Yes, since that commit the project has moved to the [PEP 517](https://www.python.org/dev/peps/pep-0517/) build system instead of using setup.py. Could you try updating `pip` and `setuptools` with
```
pip install --upgrade pip setuptools
```
since the older versions might not support this newer format, and make sure your Python version is >= 3.5, and then try installing again.

**Comment by prlw1** [comment]
Indeed! Sorry about that. (pip3 updated from ubuntu repository via apt wasn't recent enough)

**Comment by eugenhu** [comment]
No problems.
