### ISSUE TITLE
Application will stop analysing images

### ISSUE THREAD

**Issue by FelixKratz** [jdber1/opendrop#30]
When testing with ~200 images the application does not seem to analyse the images and an ever spinning progress indicator is shown. When selecting only ~50 images the analysis works as expected.  Could this have to do with multiprocessing? I experience this issue under macOS and Linux on a 6 core CPU.

**Comment by eugenhu** [comment]
It seems like when there were too many spinners, the event loop was just repeatedly invoking the spinners' animation update cycles instead of the callbacks to tell the program that fitting had completed since the animation callbacks had the same 'default' priority.

Hopefully this is fixed with https://github.com/jdber1/opendrop/commit/f79e9c4c8aaf68f7df0cd52c5fa424b8ae8db452.

Update with
```
pip install -U git+https://github.com/jdber1/opendrop.git
```
Thank you for the prompt feedback, I'll work on addressing two of your other issues tomorrow.

**Comment by FelixKratz** [comment]
It is working properly now.
