### ISSUE TITLE
release v3.3.2 on Windows cannot save processed images

### ISSUE THREAD

**Issue by github-young** [jdber1/opendrop#54]
I am using the latest release for Windows v3.3.2 and I cannot save the marked image. I only get some csv files, as shown in the screenshots
![图片](https://github.com/jdber1/opendrop/assets/19162282/3179fb38-d624-404f-9f97-132c277dbfcf)

**Comment by eugenhu** [comment]
Hi, thanks for trying out the new version. This version is just a hacky patch to implement manual image scale px/mm option to resolve #51. I don't think it should have affected what information is saved for each analysis. If I remember correctly, we removed the feature to save the annotated images many years ago since they were taking up a lot of space.

Apologies if you require this feature, but I guess the best alternative is to re-annotate the image yourself from the .csv data saved. I believe if you use a camera as an image source, the acquired (unannotated) images will still be saved.

**Comment by github-young** [comment]
OK thank you

**Comment by Akib-Shirsha** [comment]
I need some help brother, Can you please tell me the way to install on Windows 10? I'll be very much grateful if you share the process.
